"""
SentinelShield Security Logger

This module records security events generated by
the SentinelShield WAF.
"""

import logging
import os


# ============================================================
# LOG DIRECTORY
# ============================================================

LOG_DIRECTORY = os.path.join(
    os.path.dirname(os.path.dirname(__file__)),
    "logs"
)

os.makedirs(LOG_DIRECTORY, exist_ok=True)


# ============================================================
# LOG FILE
# ============================================================

LOG_FILE = os.path.join(
    LOG_DIRECTORY,
    "security.log"
)


# ============================================================
# LOGGER CONFIGURATION
# ============================================================

security_logger = logging.getLogger("SentinelShield")

security_logger.setLevel(logging.INFO)


# Prevent duplicate handlers when Flask debug mode reloads
if not security_logger.handlers:

    file_handler = logging.FileHandler(
        LOG_FILE,
        encoding="utf-8"
    )

    formatter = logging.Formatter(
        "%(asctime)s | %(message)s"
    )

    file_handler.setFormatter(formatter)

    security_logger.addHandler(file_handler)


# ============================================================
# SECURITY EVENT LOGGER
# ============================================================

def log_security_event(
    ip_address,
    attack_type,
    matched_pattern,
    path,
    action,
    severity
):
    """
    Record a security event in security.log.
    """

    message = (
        f"IP={ip_address} | "
        f"Attack={attack_type} | "
        f"Pattern={matched_pattern} | "
        f"Path={path} | "
        f"Action={action} | "
        f"Severity={severity}"
    )

    security_logger.info(message)


# ============================================================
# ALERT MESSAGE
# ============================================================

def create_alert(
    ip_address,
    attack_type,
    path,
    severity
):
    """
    Create a structured security alert.
    """

    return {
        "alert": True,
        "message": "Security threat detected",
        "attack_type": attack_type,
        "severity": severity,
        "source_ip": ip_address,
        "path": path
    }